# Auto-generated by repobuild, do not modify directly.

.gen-obj/.boost_gen.dummy: .gen-src/boost/.dummy
	(mkdir -p .gen-files; GEN_DIR=".gen-files" eval './bootstrap.sh && ./b2 toolset=clang cxxflags="-stdlib=libc++ --std=c++11 -O3 -pthread" linkflags="-stdlib=libc++ --std=c++11 -lpthread" -j8 --stagedir=.gen-files') && (mkdir -p .gen-obj; touch .gen-obj/.boost_gen.dummy)

.gen-files/lib/libboost_atomic.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_chrono.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_context.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_coroutine.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_date_time.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_exception.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_filesystem.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_graph.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_iostreams.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_log.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_log_setup.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_math_c99.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_math_c99f.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_math_c99l.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_math_tr1.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_math_tr1f.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_math_tr1l.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_prg_exec_monitor.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_program_options.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_python.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_random.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_regex.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_serialization.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_signals.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_system.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_test_exec_monitor.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_thread.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_timer.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_unit_test_framework.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_wave.a: .gen-obj/.boost_gen.dummy

.gen-files/lib/libboost_wserialization.a: .gen-obj/.boost_gen.dummy

.PHONY: 

.gen-src/boost:
	mkdir -p .gen-src; if [[ ! -a boost ]]; then mkdir -p boost; fi; ln -f -s ../boost .gen-src/boost

.gen-src/boost/.dummy: .gen-src/boost
	if [[ ! -a .gen-src/boost/.dummy ]]; then touch .gen-src/boost/.dummy; fi

clean:
	rm -f .gen-src/boost/.dummy
	rm -f .gen-src/boost
	rm -rf .gen-obj
	rm -rf .gen-files
	rm -rf .gen-src

all:

.PHONY: clean all

.DEFAULT_GOAL=all

